# you first need to run these queries on the RDF database that you are going to use
# the values returned by these queries (in a csv file) can be used to generate the queries
# actually used in our experiments

# for BSBM query 1

PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?prodType ?prodFeat1 ?prodFeat2
WHERE {
 ?product rdfs:label ?label .
 ?product a ?prodType.
 ?product bsbm:productFeature ?prodFeat1 .
 ?product bsbm:productFeature ?prodFeat2 .
?product bsbm:productPropertyNumeric1 ?value1 .
	FILTER (?value1 > 50)
    FILTER (?prodFeat1 != ?prodFeat2)
	}
# ORDER BY ?label
LIMIT 1000


# for BSBM query 2
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT distinct ?product
WHERE {
?product rdfs:label ?label .
?product rdfs:comment ?comment .
?product bsbm:producer ?p .
?p rdfs:label ?producer .
?product dc:publisher ?p .
?product bsbm:productFeature ?f .
?f rdfs:label ?productFeature .
?product bsbm:productPropertyTextual1 ?propertyTextual1 .
?product bsbm:productPropertyTextual2 ?propertyTextual2 .
?product bsbm:productPropertyTextual3 ?propertyTextual3 .
?product bsbm:productPropertyNumeric1 ?propertyNumeric1 .
?product bsbm:productPropertyNumeric2 ?propertyNumeric2 .
OPTIONAL { ?product bsbm:productPropertyTextual4 ?propertyTextual4 }
OPTIONAL { ?product bsbm:productPropertyTextual5 ?propertyTextual5 }
OPTIONAL { ?product bsbm:productPropertyNumeric4 ?propertyNumeric4 }
}
LIMIT 1000


# for BSBM query number 3
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT distinct ?product_type ?product_feature_1 ?product_feature_2
WHERE {
?product rdfs:label ?label .
?product a ?product_type .
?product bsbm:productFeature ?product_feature_1 .
?product bsbm:productPropertyNumeric1 ?p1 .
FILTER ( ?p1 > 100 )
?product bsbm:productPropertyNumeric3 ?p3 .
FILTER ( ?p3 < 300 )
OPTIONAL {
?product bsbm:productFeature ?product_feature_2 .
?product rdfs:label ?testVar
FILTER (?product_feature_1 != ?product_feature_2)}
# FILTER (!bound(?testVar)) # -- this command here makes the query impossible --
}
LIMIT 1000


# for BSBM query 5
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT DISTINCT ?pxyz
WHERE {
?product rdfs:label ?productLabel .
FILTER (?pxyz != ?product)
?pxyz bsbm:productFeature ?prodFeature .
?product bsbm:productFeature ?prodFeature .
?pxyz bsbm:productPropertyNumeric1 ?origProperty1 .
?product bsbm:productPropertyNumeric1 ?simProperty1 .
FILTER (?simProperty1 < (?origProperty1 + 120) && ?simProperty1 > (?origProperty1 - 120))
?pxyz bsbm:productPropertyNumeric2 ?origProperty2 .
?product bsbm:productPropertyNumeric2 ?simProperty2 .
FILTER (?simProperty2 < (?origProperty2 + 170) && ?simProperty2 > (?origProperty2 - 170))
}
LIMIT 1000


# for query 6
SELECT distinct ?label
WHERE {
?product rdfs:label ?label .
?product rdf:type bsbm:Product .
}
LIMIT 1000


# for query 7 - hard!
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT distinct ?pxyz ?country
WHERE {
?pxyz rdfs:label ?productLabel .
# OPTIONAL {
?offer bsbm:product ?pxyz .
?offer bsbm:price ?price .
?offer bsbm:vendor ?vendor .
?vendor rdfs:label ?vendorTitle .
?vendor bsbm:country ?country .
?offer dc:publisher ?vendor .
?offer bsbm:validTo ?date .
FILTER (?date > "2008-03-01"^^xsd:dateTime )
# }
OPTIONAL {
?review bsbm:reviewFor ?xyz .
?review rev:reviewer ?reviewer .
?reviewer foaf:name ?revName .
?review dc:title ?revTitle .
OPTIONAL { ?review bsbm:rating1 ?rating1 . }
OPTIONAL { ?review bsbm:rating2 ?rating2 . }
}
}
LIMIT 100

# query 8
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT distinct ?pxyz
WHERE {
?review bsbm:reviewFor ?pxyz .
?review dc:title ?title .
?review rev:text ?text .
FILTER langMatches( lang(?text), "EN" )
?review bsbm:reviewDate ?reviewDate .
?review rev:reviewer ?reviewer .
?reviewer foaf:name ?reviewerName .
OPTIONAL { ?review bsbm:rating1 ?rating1 . }
OPTIONAL { ?review bsbm:rating2 ?rating2 . }
OPTIONAL { ?review bsbm:rating3 ?rating3 . }
OPTIONAL { ?review bsbm:rating4 ?rating4 . }
}
LIMIT 1000

# query 10
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?productXYZ
WHERE {
?offer bsbm:product ?productXYZ .
?offer bsbm:vendor ?vendor .
?offer dc:publisher ?vendor .
?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#US> .
?offer bsbm:deliveryDays ?deliveryDays .
FILTER (?deliveryDays <= 3)
?offer bsbm:price ?price .
?offer bsbm:validTo ?date .
FILTER (?date > "2008-02-10T00:00:00"^^xsd:dateTime )
}
LIMIT 1000
